package by.epam.authorization.command;

/**
 * CommandName.class
 * Enum class contains all values
 * from JSP's tag
 * <input type="hidden" name="command" value=""/>
 * used to select needed command called user on JSP
 * @author MasSword
*/

public enum CommandName {
	LOGIN, RU, EN, REGISTRATION, RESTORE, EX_DECLARATION_CHECK, USER_PAGE, DECLARATION_CHECK, LOG_OUT,
	USER_NEW_DECLARATION, CREATE_NEW_DECLARATION, SUBMIT_NEW_DECLARATION, ADD_NEW_GOOD, SHOW_ALL_DECLARATIONS,
	DECLARATION_CHOOSE, CREATE_DECLARATION_CHANGES, SUBMIT_CHANGING_DECLARATION, CHANGE_NEW_GOOD, A_USER_REVIEW,
	A_SHOW_ALL_USERS, A_USER_CONFIRM, A_USER_DECLINE, A_SHOW_DECLARATION, ADMIN_PAGE, A_NEW_DECLARATIONS_REVIEW,
	A_DECLARATION_CONFIRM, A_DECLARATION_DECLINE, A_REGISTRATION, NO_SUCH_COMMAND;
}
